### ISSUE TITLE
잡기 페이지 알림창 떠 있을때 다른 포켓몬 잡으면 알림창이 빨리 꺼지는 이슈

### ISSUE THREAD

**Issue by jehyeon** [kyungeun-j/zzang_pika#23]

**Comment by jehyeon** [comment]
알림창이 떠있는동안 클릭을 막자

**Comment by jehyeon** [comment]
shop에서도 동일

**Comment by kyungeun-j** [comment]
catch - https://github.com/kyungeun-j/zzang_pika/commit/68cb89fe1411ee583d3db994b482e5abda2c8684
shop - https://github.com/kyungeun-j/zzang_pika/commit/6d93e3648f43f6a23774196878df4a31d43fd2c1
