### ISSUE TITLE
잡기 페이지에서 남은 볼이 0개이면 볼 이미지 회색으로

### ISSUE THREAD

**Issue by jehyeon** [kyungeun-j/zzang_pika#24]

**Comment by kyungeun-j** [comment]
https://github.com/kyungeun-j/zzang_pika/commit/8a0637abb899f1daa56db8cf2d92b18c0eeb13e0

**Comment by kyungeun-j** [comment]
https://github.com/kyungeun-j/zzang_pika/commit/485fe0b85b4750b14df6957e1b37b5132b198dbe

js 수정
