### ISSUE TITLE
체력바 갱신 만들기

### ISSUE THREAD

**Issue by jehyeon** [kyungeun-j/zzang_pika#40]
포켓몬 페이지
리로딩이 되면 체력바가 다시 그려지면서 갱신이 됨
-> 포켓몬 이동 시에는 다시 그리기 때문에 새로고침 없이 체력바 갱신이 이루어짐
```
// 초기화 <- 나중에 효율적으로 수정해야 할듯
            getClass('working')[0].children[1].innerHTML = '';
            getClass('resting')[0].children[1].innerHTML = '';
            getClass('default')[0].children[1].innerHTML = '';

            // create function 실행
            RMCreate(myPokemonJSON, rmCount);
```

- 1초마다 위 코드를 반복하면 갱신 구현이 끝남 -> 효율적인지 확인, 트래픽을 많이 잡아먹는지, 렉은 걸리는지 부자연스러운지, 드래그 도중에 갱신되면 어떻게 되는 지 등등 
- 체력바만 갱신시키기, 이때 체력바 변동은 working과 Resting에서만 진행됨
  - working은 1초에 1씩 깎임, HP 600은 600초, 10분
    - working은 1초마다 startHp를 1 감소, 그 비율에 맞게 체력바 width 재계산
  - Resting은 24시간 (86400) 기준 체력 100% 회복
    - 체력 300, 1800 둘다 꽉 채우는데 12시간이 걸림
    - 1초마다 전체 체력 * 1/43200 이 늘어남 -> 5분 간격으로 계산해도 좋을듯

**Comment by kyungeun-j** [comment]
db5356bee7eea775a477354ff2b0e1043f5411c8
